feat(lobbies.list_regions): return regions sorted by proximity to client
rivet-gg/modules pull request #581
Opened 2024-09-19 21:04 UTC by ABCxFF

2024-09-19 21:05 UTC, ABCxFF commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/modules/581?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#581** <a href="https://app.graphite.dev/github/pr/rivet-gg/modules/581?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#578** <a href="https://app.graphite.dev/github/pr/rivet-gg/modules/578?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#577** <a href="https://app.graphite.dev/github/pr/rivet-gg/modules/577?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#576** <a href="https://app.graphite.dev/github/pr/rivet-gg/modules/576?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ABCxFF and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-27 08:06 UTC, NathanFlurry requested changes
- the logic is incorrect for captchas. captchas are supposed to require a captcha on the first request.
- this module needs better doc comments about all of the scripts. 
- the scripts are missing description.
- the module is missing an icon & tags & description.
- don't commit the deno.lock. this might be an issue with the toolchain.
- make sure to run `rivet module format` and `rivet module lint`

2024-09-27 08:21 UTC, NathanFlurry commented on modules/lobbies/utils/rivet/geo_coord.ts
> +    if (ctx.environment.get("MANAGED") !== "1") return EMPTY_GEO_COORDS;
`RIVET_BACKEND_RUNTIME=cloudflare_workers_platforms`. this matches the `rivet backend build --runtime` flag.

2024-09-27 08:21 UTC, NathanFlurry commented on modules/lobbies/utils/rivet/geo_coord.ts
> +    // TODO: Only check the first/last entry
should not leave any todos

2024-09-27 08:22 UTC, NathanFlurry commented on modules/lobbies/utils/rivet/geo_coord.ts
> +    if (!httpReq) return EMPTY_GEO_COORDS;
return undefined since it's not available. this could easily cause an accidental lookup with empty coords and lead to obscure errors.

2024-09-27 08:23 UTC, NathanFlurry commented on modules/lobbies/utils/rivet/geo_coord.ts
> +    if (!httpReq.headers["x-backend-client-coords"]) return EMPTY_GEO_COORDS;
throw error, this should be unreachable. prefer to fail by default.

2024-09-27 08:24 UTC, NathanFlurry commented on modules/lobbies/utils/rivet/geo_coord.ts
> +    // TODO: Optimize this
remaining todo

2024-09-27 08:24 UTC, NathanFlurry commented on modules/lobbies/utils/rivet/geo_coord.ts
> +    const coords = httpReq.headers["x-backend-client-coords"].split(",").map(e => parseFloat(e.trim()));
would be cleaner as a destructure

2024-09-27 08:24 UTC, NathanFlurry commented on modules/lobbies/utils/region.ts
everything in this file should use export function not export const

2024-09-27 08:25 UTC, NathanFlurry commented on modules/lobbies/utils/region.ts
> +const getDistSq = (a: RegionGeoCoords, b: RegionGeoCoords) => {
this won't work for lat/long. look up the code for this.

2024-09-27 08:26 UTC, NathanFlurry commented on modules/lobbies/utils/region.ts
> +  if (coords === EMPTY_GEO_COORDS) return region[0];
return undefined, not a default valid.

2024-09-27 08:26 UTC, NathanFlurry commented on modules/lobbies/utils/region.ts
> +  if (coords === EMPTY_GEO_COORDS) return [...regions];
see above

2024-12-13 10:30 UTC, closed without merging